### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Alejandro12120** [Sprayxe/valorant.js#5]
Hey, I am using this code:
```js
(async () => {

    const Valorant = require('valorant.js');

    try {
        const client = new Valorant.Client({
            username: "USERNAME",
            password: "PASSWORD",
            region: Valorant.region.eu,
            debug: true
        });


        const account_data = await client.login();
        console.log(account_data);


    } catch (err) {
        console.error(err);
    }


})();
```

But I get this error:
```
(node:10716) UnhandledPromiseRejectionWarning: C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\parsers\store.js:33
              name: (this.getItem(item.Item.ItemID))?.name,
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\main\valorant\index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
(node:10716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by BobbyESP** [comment]
Are you putting the username and the password??

**Comment by Alejandro12120** [comment]
Yes

**Comment by BobbyESP** [comment]
Ok. Let me fix the library. Riot changed the login system a few days ago. Maybe is that.

**Comment by Alejandro12120** [comment]
Alright

**Comment by BobbyESP** [comment]
Ok, it's fixed. Try now merging the update wit your version.

**Comment by Alejandro12120** [comment]
According to npm, the latest version of valorant.js was released 4 months ago. 
![image](https://user-images.githubusercontent.com/45500329/104220007-27a91f80-543f-11eb-87bb-4d29af597e7d.png)

**Comment by BobbyESP** [comment]
i haven't the permissions to upload it to npm, so let me talk to @Speeedyyyy

**Comment by FPilica** [comment]
I can't push to npm pretty sure so wait for @Sprayxe

**Comment by BobbyESP** [comment]
Ok. I talked to Spay and he updated the project to NPM. Try now. Thxx

**Comment by Alejandro12120** [comment]
It doesn't work, the same error.

**Comment by marcel-wrld** [comment]
Yea I've seen people having issues with "?." stuff. The "?" before the "." should basically prevent from running into an error like "cannot read property 'x' of undefined/null" (instead of that error, it just returns "undefined"). I will deploy a fix

**Comment by marcel-wrld** [comment]
I've updated the package. Could you update it and let me know if it works?

**Comment by Alejandro12120** [comment]
Now it displays this error.

```
(node:10972) UnhandledPromiseRejectionWarning: C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\parsers\store.js:29
          const it
                ^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\main\valorant\index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
(node:10972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by marcel-wrld** [comment]
Ohh, my bad. Lol I don't know what I have done there xD. Lemme fix it quick

**Comment by marcel-wrld** [comment]
I've updated the package, lmk if it works now

**Comment by Alejandro12120** [comment]
Now it displays this error.

```
(node:14100) UnhandledPromiseRejectionWarning: C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\parsers\store.js:78
      const item = storefront.find(item => item?.id === id);
                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Alejandro\Desktop\Valorant\node_modules\valorant.js\src\main\valorant\index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    ```

**Comment by marcel-wrld** [comment]
Yea I will go through the files and remove all "?."

**Comment by marcel-wrld** [comment]
My bad, i was busy and forgot about it. It should work now. install the newest version using 'npm i valorant.js'

**Comment by Alejandro12120** [comment]
It worked thanks

**Comment by BobbyESP** [comment]
Can i ask you what are u developing?? (Just curious, kek)

**Comment by Alejandro12120** [comment]
just testing stuff

**Comment by BobbyESP** [comment]
okk
